### ISSUE TITLE
Demangle c++ symbols

### ISSUE THREAD

**Issue by Petross404** [horsicq/XELFViewer#1]
Hello, I am experimenting with XELFViewer and I like it. One thing I thought to share with you, is that it would be a nice feature for XELFViewer to optionally demangle c++ symbols with `c++filt` on Linux.

I can't think of a crossplatform solution but on Linux c++filt is very good.

All the best,
Petros

**Comment by horsicq** [comment]
Hello Petros, thanks a lot for the inreresting idea! I will take a look.

**Comment by Petross404** [comment]
Cool!

**Comment by horsicq** [comment]
It will be in the next version.

![image](https://user-images.githubusercontent.com/7762949/112146476-e6ba4d80-8bdb-11eb-8447-f7b2bb16766b.png)
![image](https://user-images.githubusercontent.com/7762949/112146497-ed48c500-8bdb-11eb-8949-7f04b540d5c9.png)
![image](https://user-images.githubusercontent.com/7762949/112146526-f6399680-8bdb-11eb-9760-a8524982d3be.png)
