### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by knowonething** [horsicq/XELFViewer#2]
My installation failed.
At start, it said:
WARNING: Failure to find: $HOME/XELFViewer/XHexView/xhexviewwidget.ui
Later it said it could not find "../XHexView/xhexviewwidget.ui" and terminates the installation.
I checked the folder on github, and there is no such file.

**Comment by horsicq** [comment]
Thanks a lot for the report! Could you try again? I made a commit: https://github.com/horsicq/XELFViewer/commit/a5f16063a37c72e046ef6fa360f8bbaee26a6c50

**Comment by knowonething** [comment]
Thanks, it works now.
