### ISSUE TITLE
crash when editing section header table

### ISSUE THREAD

**Issue by RA19HS** [horsicq/XELFViewer#24]
Hi,
**This crash report is for commit e5f9019ff5a64edefd6b14c9776b998b176f7c58**
It crashes when I change flag of
**.text** section to make it writable.
Can you fix it, or hint us how to fix it?
Best regards,
R. A.

**Comment by horsicq** [comment]
Hello! Thanks a lot for the bugreport! It crashes on all files or on some files?

**Comment by RA19HS** [comment]
All ELF-64 files.
10 files tested.

When I comment first line of function **XComboBoxEx::setValue(quint64 nValue)**,
line 82 in file XELFViewer/Controls/xcomboboxex.cpp,
it won't crash, so this line is where the program receives **SIGSEGV** (signal confirmed by **strace**).
But it can change ELF header.

ELF header of one of my files:
> readelf -h ~/.../elf.out
ELF Header:
  Magic:   7f 45 4c 46 02 01 7b 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           123 <unknown>
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1e1b9
  Entry point address:               0x31a0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          254296 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         12
  Size of section headers:           64 (bytes)
  Number of section headers:         32
  Section header string table index: 31

Thanks for your fast response.

**Comment by RA19HS** [comment]
And when the program crashes, my _Desktop Environment_ **freezes** (except mouse).
Unfortunately this is the case when I start debugging in Qt;
Then I should go to another **TTY** and kill the program.

My system:
> \> uname -a
Linux ... 5.11.0-41-generic #45\~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

> \> gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1\~20.04) 9.3.0
...

**Comment by horsicq** [comment]
Thanks a lot for the file. Fixed: https://github.com/horsicq/FormatWidgets/compare/c2700d852aabef5be4456b6ad38db70980e70f32...8ee35289eadaa22e171673b0dee15639498842c2#diff-e559052cacc4a3ef2095b35c1c8ca833132ecbb411fa982fe93b85a3353938f9

**Comment by RA19HS** [comment]
Thanks.
The program works smoothly.
