### ISSUE TITLE
Cannot EDIT Elf File 

### ISSUE THREAD

**Issue by kies83** [horsicq/XELFViewer#27]
Hey Dev!

I have used you windows app 64 bit and loaded elf file into it all details are fine and working but i want to make change in some points . I have also unchecked box readonly . to make writable but its not working and saving the text i add

**Comment by horsicq** [comment]
Thanks for the report! I will take a look.

**Comment by kies83** [comment]
waiting for the moment..

**Comment by kies83** [comment]
could you share your discord or Mail to send file on which i am testing.

**Comment by horsicq** [comment]
horsicq@gmail.com
I made a special Telegram Bot for files: @detectiteasy_bot you could use it too

**Comment by kies83** [comment]
@horsicq Thanks for replying I have sent files through discord 

_Sent from my Infinix X655C using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kies83** [comment]
I have sent files through discord server plz check

**Comment by horsicq** [comment]
I got your email. Thanks a lot!

**Comment by kies83** [comment]
I am running version  64 bit windows thus the app i used also 64 bit. I have used hxd editor to modify such files. but after modifying when i run file in terminal. it shows an error readelf: dl open failed invalid shdr offset/size. maybe header is corrupted waiting for your response

**Comment by horsicq** [comment]
Ok. Thanks. I will take a look.

**Comment by kies83** [comment]
Any news brother?

**Comment by horsicq** [comment]
I am making now other projects. :(

**Comment by kies83** [comment]
Related to this problem or others??

**Comment by horsicq** [comment]
Others.

**Comment by kies83** [comment]
So how many time it will take??

**Comment by horsicq** [comment]
Hmm. I do not know. What do you want to do with your file? Write me to my email or Telegram.

**Comment by kies83** [comment]
I just want to know.. coz i am a tester..noob just trying some methods to make change in it. I also have used hxd editor. But after using this the readelf file header get corrupted

**Comment by kies83** [comment]
Any news??

**Comment by horsicq** [comment]
I have to make now other projects. :(

**Comment by kies83** [comment]
Then you are not solving my problem???

**Comment by horsicq** [comment]
I will solve your problem later.

**Comment by horsicq** [comment]
I sent you an e-mail.

**Comment by young1112** [comment]
@kies83 can you help me decrypt a file
