### ISSUE TITLE
Incorrect relocation types are displayed

### ISSUE THREAD

**Issue by filipnavara** [horsicq/XELFViewer#30]
The R_X86_64_64 relocation is incorrectly displayed as R_X86_64_32:

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/1764393/196705289-f64c596e-b793-453f-a85e-77cdcd8955d8.png">

Test file: [Exceptions.zip](https://github.com/horsicq/XELFViewer/files/9820897/Exceptions.zip)

**Comment by horsicq** [comment]
Fixed
![image](https://user-images.githubusercontent.com/7762949/196892220-daaa8475-44c9-43f1-a40a-bc223eb7427c.png)

https://github.com/horsicq/XELFViewer/releases/download/Beta/xelfviewer_win32_portable_0.06.zip

**Comment by filipnavara** [comment]
Thanks!

**Comment by horsicq** [comment]
You are welcome! If you need new features or you have any new ideas just let me know. :)
