### ISSUE TITLE
Type value in Programs.Notes miss high word part

### ISSUE THREAD

**Issue by fish2bird** [horsicq/XELFViewer#34]
I use XELFViewer analyse a coredump file,  I want to inpsect data in note: NT_SIGINFO

as https://elixir.bootlin.com/linux/v4.5/source/include/uapi/linux/elf.h#L376
```
#define NT_SIGINFO      0x53494749
```

0x53494749 be seen in hexdump
but XELFViewer  parsed Type = 0x00004749

BTW, all Type field for each note seems miss higher 2 bytes

**Comment by horsicq** [comment]
Hello! Thanks a lot for the bugreport! Could you please share your screenshot of XELFViewer?

**Comment by fish2bird** [comment]
> Hello! Thanks a lot for the bugreport! Could you please share your screenshot of XELFViewer?

![image](https://user-images.githubusercontent.com/5350679/217204143-a28f700e-8e62-4db3-ac46-d29de514b9fb.png)

**Comment by horsicq** [comment]
Thanks a lot! It will be fixed in 1-2 days and a beta version with this fix will be here: https://github.com/horsicq/XELFViewer/releases/tag/Beta

**Comment by horsicq** [comment]
Fixed
