### ISSUE TITLE
How to open multiple instances at the same time on macOS

### ISSUE THREAD

**Issue by sledgeh4w** [horsicq/XELFViewer#36]
I can't find an effective way to view multiple files at the same time. Hope to support that. Thanks!

**Comment by stuti-singh-in** [comment]
you can open multiple instances of some applications from the command line.
For example, to open multiple instances of the "TextEdit" application, you can use the open command with the -n option:

open -n /Applications/TextEdit.app

**Comment by stuti-singh-in** [comment]
If you have a specific application in mind that you want to open multiple instances of, let me know, and I can provide more detailed instructions for that particular file.

**Comment by sledgeh4w** [comment]
Thanks for your reply.
