### ISSUE TITLE
Cannot parse a file with a large number of grouped sections

### ISSUE THREAD

**Issue by filipnavara** [horsicq/XELFViewer#37]
Sample file: [Reflection_FromUsage.zip](https://github.com/horsicq/XELFViewer/files/12801288/Reflection_FromUsage.zip)

**Comment by horsicq** [comment]
Thanks a lot for the bugreport! It will be fixed.

**Comment by filipnavara** [comment]
Thanks! I didn't find any viewer able to parse this (aside from `objdump` and `readelf` command line tools), so a fix would be appreciated.

**Comment by filipnavara** [comment]
In case it's useful, I found the relevant part of the ELF specification:

> If the number of sections is greater than or equal to SHN_LORESERVE (0xff00), e_shnum has the value SHN_UNDEF (0) and the actual number of section header table entries is contained in the sh_size field of the section header at index 0 (otherwise, the sh_size member of the initial entry contains 0).

**Comment by horsicq** [comment]
> In case it's useful, I found the relevant part of the ELF specification:

Thanks a lot! I added this rule right now. :)

**Comment by filipnavara** [comment]
There's one more odd case I found. Not sure if it's handled:

> e_shstrndx
>
> This member holds the section header table index of the entry associated with the section name string table.  If the file has no section name string table, this member holds the value SHN_UNDEF.
>
> If the index of section name string table section is larger than or equal to SHN_LORESERVE (0xff00), this member holds SHN_XINDEX (0xffff) and the real index of the section name string table section is held in the sh_link member of the initial entry in section header table. Otherwise, the sh_link member of the initial entry in section header table contains the value zero.

**Comment by horsicq** [comment]
> There's one more odd case I found. Not sure if it's handled:

I will fix it too. :)

**Comment by horsicq** [comment]
Fixed:
https://github.com/horsicq/XELFViewer/releases/tag/Beta

**Comment by filipnavara** [comment]
Thanks! The large number of sections now work.

A related thing I want to mention is that the `st_shndx` field of symbol table can have the `SHN_XINDEX` value (0xffff). The actual section number is then resolved from another table in a different ELF section that links to the original symbol table. That's not necessarily an issue since I don't expect the values to be resolved in the current UI. If you ever decide to expand on the Symbol Table view, you should keep it in mind though.

**Comment by horsicq** [comment]
Thanks for the information! I will think about the symbol table.
