### ISSUE TITLE
Release needs to add libQt5OpenGL.so.5

### ISSUE THREAD

**Issue by jstaursky** [horsicq/XELFViewer#4]
Hey so I havent been able to build because of 
```
../FormatWidgets/SearchStrings/searchstringswidget.h:34:10: fatal error: dialogmultisearchprocess.h: No such file or directory
   34 | #include "dialogmultisearchprocess.h"

```
Error
but fortunately it still packaged up a libQt5OpenGL.so.5 which enabled me to run your release build.
So you might want to add that

**Comment by horsicq** [comment]
Thanks a lot for the bugreport! 

I fixed it https://github.com/horsicq/XELFViewer/commit/2c060cbef7a34373cd6f63f5d389c4c3e8d05a35
